project-name: rogryza.me
base-path: /
context:
  static:
    site-title: rogryza.me
    author: Rodrigo Gryzinski
    repository: https://github.com/RoGryza/blog
    contact: contact@rogryza.me
  dynamic:
    languages: session.query(Lang).order_by(Lang.rank).all()
templates:
  providers:
    - jinja2
