project-name: rogryza.me
base-path: / # https://blog.rogryza.me
context:
  static:
    site-title: rogryza.me
    author: Rodrigo Gryzinski
    repository: https://github.com/RoGryza/blog
    site-description:
      en: programming ramblings
      pt: divagações sobre programação
    view-source:
      en: View source
      pt: Ver código fonte
  dynamic:
    languages: session.query(Lang).order_by(Lang.rank).all()
templates:
  providers:
    - jinja2
