base_url = "https://blog.rogryza.me"

compile_sass = true
highlight_code = true
build_search_index = false

title = "rogryza.me"
# TODO translate description
description = "Rodrigo Gryzinki's programming blog"

languages = [
  { code = "en-us", feed = true },
  { code = "pt-br", feed = true },
]

[extra]
author = "Rodrigo Gryzinski"
