base_url = "https://blog.rogryza.me"

theme = "lightspeed"

highlight_code = true
highlight_theme = "gruvbox-light"

title = "rogryza.me"
description = "Rodrigo Gryzinki's programming blog"

generate_feed = true

default_language = "en"

taxonomies = [
  { name = "tags" },
]

[extra]
author = "Rodrigo Gryzinski"
nav_links = [
  { url = "$BASE_URL/pages/now/", name = "/now" },
  { url = "$BASE_URL/pages/about/", name = "About me" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  { url = "$BASE_URL/atom.xml", name = "RSS" },
  { url = "https://github.com/RoGryza/blog", name="View source" },
]
