project-name: rogryza.me
base-path: https://blog.rogryza.me
theme: lightspeed
context:
  static:
    site-title: rogryza.me
    author: Rodrigo Gryzinski
    repository: https://github.com/RoGryza/blog
    git_ref: master
    site-description:
      en: Rodrigo Gryzinski's personal programming blog
      pt: Blog pessoal de programação do Rodrigo Gryzinski
    view-source:
      en: View source
      pt: Ver código fonte
  dynamic:
    languages: session.query(Lang).order_by(Lang.rank).all()
templates:
  providers:
    - jinja2
