project-name: rogryza.me
base-path: /
context:
  static:
    site-title: rogryza.me
    author: Rodrigo Gryzinski
    base-url: https://blog.rogryza.me
    repository: https://github.com/RoGryza/blog
    site-description:
      en: Rodrigo Gryzinski's programming blog
      pt: blog de programação do Rodrigo Gryzinski
    view-source:
      en: View source
      pt: Ver código fonte
  dynamic:
    languages: session.query(Lang).order_by(Lang.rank).all()
templates:
  providers:
    - jinja2
