name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DART_VERSION: 1.39.2
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Pre-publish
        run: nix develop --command scripts/pre-publish.sh
        env:
          WRANGLER_ACCOUNT_ID: ${{ secrets.WRANGLER_ACCOUNT_ID }}
          WRANGLER_ZONE_ID: ${{ secrets.WRANGLER_ZONE_ID }}
      - name: Build
        run: nix develop --command scripts/build.sh
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
