name: Publish
on:
  push:
    branches:
      - TODOmaster
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: 0.13.0
      ZOLA_HASH: 1a919e00cce61e30c31cd8d0979349ecd3f7c1666d32fa77314cbfbb89447adb
    steps:
      - uses: actions/checkout@v2
        with:
          # The theme is a submodule
          submodules: recursive
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - name: Fetch and check zola binary
        run: |
          wget "https://github.com/getzola/zola/releases/download/v0.13.0/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" -O zola.tar.gz && \
          echo "${ZOLA_HASH}  zola.tar.gz" | sha256sum --check && \
          tar xzf zola.tar.gz && chmod +x zola
      - name: Build
        run: ./zola build
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
